version: "3.8"

services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - mysqldb
    container_name: back-end
    networks:
      mpec:

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mpecdb
    ports:
      - "3309:3306"
    networks:
      mpec:

networks:
  mpec: